### ISSUE TITLE
Access violation writing location

### ISSUE THREAD

**Issue by Redacted00** [iwer/GeotiffLandscape#7]
Hi! When I tried to import my GeoTiff file, i had this error in Visual Studio in `Array.h` file. 

UE 4.27

![devenv_nPrDHncIww](https://user-images.githubusercontent.com/38829120/232122171-449073c9-ab55-48ca-bc6c-de257d4fcc1f.png)

What should I do?

**Comment by iwer** [comment]
I tried to reproduce this with my test data, but couldn't.
I assume this is triggered in UGeotiffRasterScaler on adding Values to the TargetPixel TArray by the Callstacks third frame.

From here I can only guess:

Could it be, that the geotiff file covers a very large area? 
So that when it gets scaled with the geographic information it is too large to fit in memory?

If thats the case, you probably have to tile the geotiff file and use [UE World Composition](https://docs.unrealengine.com/4.27/en-US/BuildingWorlds/LevelStreaming/WorldBrowser/)

The other possibility is, that I overlooked something when filtering valid Geographic Coordinates Reference Systems so that exactly this scaling gets messed up. Whats the CRS of your Geotiff file?
